---

- hosts: all
  become: true
  pre_tasks:

  - name: Ubuntu Update
    tags: always
    apt:
      update_cache: yes
      upgrade: dist
    when: ansible_distribution == "ubuntu"


- hosts: Ubuntu_controler
  become: true
  roles:
    - role: Keystone
    - role: glance
    - role: nova
